Fix #49: Download IPFS component from ipfs/ipfs-dev.bravesoftware.com
brave/go-update pull request #50
Opened 2020-09-06 23:53 UTC by jumde

Fix #49

2020-09-09 14:13 UTC, bbondy requested changes
just a couple of copy/paste issues to fix, otherwise lgtm. 
Thanks!

2020-09-09 14:13 UTC, bbondy commented on docker-compose-prod.yml
> +      - S3_EXTENSIONS_BUCKET_HOST_TOR=ipfs.bravesoftware.com
s/S3_EXTENSIONS_BUCKET_HOST_TOR/S3_EXTENSIONS_BUCKET_HOST_IPFS

2020-09-09 14:13 UTC, bbondy commented on extension/utils.go
> +// GetS3IPFSExtensionBucketHost returns the url to use for accessing tor client crx
s/tor/go-ipfs

2020-09-09 23:37 UTC, bbondy approved these changes

2020-09-09 23:44 UTC, yrliou approved these changes
LGTM

2020-09-09 23:50 UTC, linhkikuchi commented
deployed this change to go-updater-dev

2020-09-10 10:28 UTC, mihaiplesa approved these changes

2020-09-10 17:43 UTC, merged